### ISSUE TITLE
Adding support for Companies - Feature Request

### ISSUE THREAD

**Issue by Nacholebraa** [ChestShop-authors/ChestShopNotifier#42]
Perhaps adding support for companiesreloaded for chest shop transactions logs. Perhaps make it so  the command is
 `/csn phistory` or `/csn chistory` | After looking at our DM'S on spigot, you could make it based only company owners can check for company transactions logs.

**Comment by Phoenix616** [comment]
After thinking a bit about this it is really something that the plugin providing the grouping feature would have to implement as this plugin has no idea with which id any other plugin implements their shops. (Also any other commands e.g. for cleaning would have
