### ISSUE TITLE
[Request] ItemAliases

### ISSUE THREAD

**Issue by x1p** [ChestShop-authors/ChestShopNotifier#43]
Recently Chestshop introduced ItemAliases. Filling these itemaliasses with some data, we noticed that `csn history` still displays the internal materialname#XY.

Example:
ItemAliases.yml
```yaml
Enchanted Book#1: Mending
Enchanted Book#2: Silk touch
```
Csn history would show `EnchantedBook#1`

Could it be possible to display the sign name instead for those items that have an alias?

**Comment by Phoenix616** [comment]
I took a look at the code and couldn't notice anything in particular which would block this at least for new items. Old items currently don't get translated though. Can you check if the alias shows up for new trades after adding it?

**Comment by x1p** [comment]
Made a fresh chest with an item which exists in the alias file for a while now.
Still the message is:
Player123 bought 1xEnchantedBook#2 14 sec ago (+ $ 1)
Instead of:
Player123 bought 1xMending 14 sec ago (+ $ 1)

**Comment by Phoenix616** [comment]
Thank you for confirming that. I'll have to look into this some more then.
