### ISSUE TITLE
Issue with {player} as "unknown"

### ISSUE THREAD

**Issue by mare-on** [ChestShop-authors/ChestShopNotifier#47]
Hi, I have an issue, latest build fixed compatibility issue with newest chestshop build but tag `{player}` is not working...

![unknown](https://user-images.githubusercontent.com/16023709/108509766-f33a4600-72bd-11eb-8fdf-a3b0ccbe0d17.png)

Version of ChestShop: 3.12-b276
Version of Notifier: 1.3.3-b45
Version of Paper: 1.16.5-b470

Console is clear, no errors after using some of the `/csn` command.

**Comment by Phoenix616** [comment]
Was the transaction made before or after you updated?

Because if it was made before then no player name was recorded for that and the plugin cannot display info about the player if they aren't online and have no ChestShop account (which only gets created once one shop is created)

**Comment by mare-on** [comment]
Hey, thanks for the tip, the transactions before update has this issue, new transactions are OK.
