### ISSUE TITLE
After updating to latest ChestShopNotifier 

### ISSUE THREAD

**Issue by andrewkm** [ChestShop-authors/ChestShopNotifier#48]
After updating to latest ChestShopNotifier Build 46 a large amount of players are complaining that there is constant unknowns showing in their chestshop history. Build 45 doesn't have this issue, build 46 continuously does at random times.
https://i.imgur.com/X4pxaMK.png

**Comment by Phoenix616** [comment]
Build 45 should have that issue more than build 46 🤔
