### ISSUE TITLE
ChestShop Notifier not working

### ISSUE THREAD

**Issue by Laukage** [ChestShop-authors/ChestShopNotifier#50]
I'm getting this error constantly..

https://paste.md-5.net/lomecajito.sql

latest version of chestshop and Chestshopnotifier - i'm using SQLITE for data storing.

**Comment by Phoenix616** [comment]
You are running an old ChestShop version, update to the latest dev build.

**Comment by Laukage** [comment]
> You are running an old ChestShop version, update to the latest dev build.

Well now chestshop broke completely and neither is working now :))

**Comment by Phoenix616** [comment]
If you have issues with ChestShop then please use it's related support systems/channels.

**Comment by Laukage** [comment]
I've now tried this plugin multiple times over a course of a year.. it has always failed when i tried to either because chestshop messed up something or because this plugin messed up something - will it ever get better because I'm pretty tired of it..

**Comment by Phoenix616** [comment]
The latest dev builds of both ChestShop and CSN work just fine on my server.
