### ISSUE TITLE
Special character

### ISSUE THREAD

**Issue by luchs888** [ChestShop-authors/ChestShopNotifier#56]
Hey,
Your plugin turned out really well!
Very good work!

Unfortunately, there is still a small user-specific error.

The symbols Ü Ä Ö etc. are unfortunately not displayed correctly.
This is especially a problem when playing on a German Server :P

-luchs888

**Comment by Phoenix616** [comment]
Please make sure you are using a proper UTF8 encoding for your language file.

**Comment by luchs888** [comment]
Uh yeah thanks.
It works now. 
:P...

**Comment by PlayingWithPi** [comment]
Close this ?
