### ISSUE TITLE
Admin Shop not ignored w/ custom name

### ISSUE THREAD

**Issue by Tsuser1** [ChestShop-authors/ChestShopNotifier#57]
Purchases made via an admin shop where the name has been changed from "`Admin Shop`" in ChestShop are not ignored.
![image](https://user-images.githubusercontent.com/3497259/148700953-d24c5946-6bbb-4d76-ac48-db6e01649ddb.png)
![image](https://user-images.githubusercontent.com/3497259/148700982-c4cda14c-d052-4061-ae06-e65c403cbd72.png)

**Comment by Phoenix616** [comment]
Doesn't look possible as far as I can tell. Please provide the command you ran to access that, your plugin config as well as your chestshop config.

**Comment by Tsuser1** [comment]
Command used: `/csn history Server Shop`
ChestShop config (irrelevant entries omitted):
```yaml
# First line of your Admin Shop's sign should look like this:
ADMIN_SHOP_NAME: "Server Shop"
```

**Comment by Phoenix616** [comment]
> CSN config hasn't been modified.

I mean if you don't disable the [logging of the admin shop](https://github.com/ChestShop-authors/ChestShopNotifier/blob/master/src/main/resources/config.yml#L4-L5) in the CSN config then how do you expect it to get ignored?

**Comment by Tsuser1** [comment]
I was under the assumption it wouldn't write entries for the admin shop into the database as that would be unnecessary?

**Comment by Phoenix616** [comment]
Well historically it used to track all shops until the config option was added (which defaults to tracking to not break existing setups). Some just want to see how their admin shop is used I guess, for the rest the config option exists.
