### ISSUE TITLE
Non-void type boolean error message

### ISSUE THREAD

**Issue by PlayingWithPi** [ChestShop-authors/ChestShopNotifier#59]
Just updated to the newest version of Paper #164, and the following message was thrown into console.

`
20.01 01:04:57 [Server] WARN @EventHandler method com.wfector.notifier.ChestShopNotifier#onChestShopTransaction returns non-void type boolean. This is an unsupported behavior which will be removed in a future version of Paper.This should be reported to the developers of ChestShopNotifier v1.3.3 (build 51), (BetaBlaze,Phoenix616,FrankHeijden)
`

**Comment by Phoenix616** [comment]
Thanks for bringing that to my attention.
