### ISSUE TITLE
Csn history calculation wrong

### ISSUE THREAD

**Issue by x1p** [ChestShop-authors/ChestShopNotifier#61]
CSN makes errors in calculation.
There is a difference between the real sell in chestshop data and the data stored in csn's database.

Example:
Seller makes a sign:
4 bone for $ 0.10
Someone buys it.
Chesthop tells buyer: ` You bought 4 Bone from PlayerSeller for $ 0.10` 
CSN shows to seller: ` PlayerBuyer bought 4xBone 12s ago (+0.03)` 
![Screenshot 2022-01-30 172537](https://user-images.githubusercontent.com/28690790/151708040-87a71a17-dfaa-4382-b5ec-4685981c60af.png)

CSN build 54
Chestshop build 341
Paper 1.18.1

**Comment by Phoenix616** [comment]
Did that change with the latest builds?

**Comment by x1p** [comment]
Yes csn build 53 works fine
